set nocompatible        " work in an improved way

" pathogen
runtime! autoload/pathogen.vim
silent! call pathogen#helptags()
silent! call pathogen#runtime_append_all_bundles()

" general
syntax on               " syntax highlighting
scriptencoding utf-8
filetype plugin indent on   " filetype detection
set mouse=a
set history=1000
set backspace=indent,eol,start
set noerrorbells
set spell

" UI
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=16
colorscheme solarized

if has('cmdline_info')
    set ruler                   " show the ruler - cursor position
    set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%) " a ruler on steroids
    set showcmd                 " show partial commands in status line and
                                " selected characters/lines in visual mode
endif

if has('statusline')
    set laststatus=2
    " Broken down into easily includeable segments
    set statusline=%<%f\    " Filename
    set statusline+=%w%h%m%r " Options
    set statusline+=%{fugitive#statusline()} "  Git Hotness
    set statusline+=\ [%{&ff}/%Y]            " filetype
    set statusline+=\ [%{getcwd()}]          " current dir
    set statusline+=%=%-14.(%l,%c%V%)\ %p%%  " Right aligned file nav info
endif

set showmode
set showmatch
set incsearch       " search as you type
set hlsearch        " highlight matches
set ignorecase      " case insensitive search
set cursorline
set number          " display a line number in front of every line
set scrolljump=5
set scrolloff=3
set list            " display whitespace characters
" setup a way of showing whitespace characters
set listchars=tab:,.,trail:.,extends:#,nbsp:.

" formatting
set nowrap              " do not wrap the text
set autoindent          " use the indent of the previous line
set smartindent
set shiftwidth=4
set expandtab
set tabstop=4
set softtabstop=4
set pastetoggle=<F12>

" mappings
let mapleader=','
nnoremap ; :
cmap cwd lcd %:p:h
nmap <F6> :set spell!<CR>
nmap <F7> :TagbarToggle<CR>

