set nocompatible

" pathogen
runtime! autoload/pathogen.vim
silent! call pathogen#helptags()
silent! call pathogen#runtime_append_all_bundles()

syntax on
scriptencoding utf-8
filetype plugin on

set background=dark
set mouse=a
set history=1000
set backspace=indent,eol,start
set ruler
set showcmd
set incsearch
set hlsearch
set ignorecase
" set number
set noerrorbells
set nowrap
set showmatch
set mat=5

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set statusline=%F%m%r%h%w\ [TYPE=%Y]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2

